### PR TITLE
Add Travis config and script

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
@nselliott - do you have an opinion on  how many configurations we test? Right now, this is just doing GCC + OpenMPI.

**Comment by nselliott** [comment]
Probably it's best to keep it small at first.  Can we do clang?  I'd say gnu and clang, and we can add more later.

**Comment by davidbeckingsale** [comment]
Good idea - I'll add clang. I'm going to leave these as 'build only' for now. And we can add some short-running tests at a later date.

**Comment by davidbeckingsale** [comment]
@nselliott - I think we should merge this, even just for GCC, to give us a compile test that helps sanity check PRs. We can expand the compiler matrix later, I'm working on improving our container images.

**Pull request merged**
