### PR TITLE
fix implicit conversion error of int to tbox::Dimension

### PR DESCRIPTION
**Pull request by monwarez**
With "recent" `gcc` compiler, `int` cannot be implicitly converted to `SAMRAI::tbox::Dimension` which is the correct behaviour since we have 
```/**
    * Constructor for Dimension, object is built using the specified dimension
    *
    * Note that the constructor is "explicit" thus making automatic
    * type conversions from integers impossible.  This is intentionally to
    * avoid unintended conversions.
    *
    * @pre (dim > 0) && (dim <= SAMRAI::MAX_DIM_VAL)
    */
   explicit Dimension(
const unsigned short& dim);
```

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
Hey @monwarez thanks for this PR! We are in the process of revitalizing SAMRAI's GitHub repository, and should merge this in the next few weeks. Thanks very much for your contribution - I am a SAMRAI developer and I've already hit this bug myself a couple of times :)

**Comment by monwarez** [comment]
You are welcome

**Comment by davidbeckingsale** [comment]
For our internal use, all compilers support at least a subset of C++11. I'm not sure on the status of all external users.

Why?

**Comment by monwarez** [comment]
It is our understanding you guys still have a boost dependency mostly for smart pointers instead of using those of C++11 standard because some of the compilers you have to deal with don't support C++11. On our side, we’d love not to have this boost dependency of course. Is there any plan on your side to remove it at some point?

**Comment by davidbeckingsale** [comment]
Pretty much. We have an internal branch that switches to `std::shared_ptr`, that should be available soon. There are a couple of other places we use boost: `unordered_map`, and `tribool`; I have branches removing those too, so stay tuned 😄

**Comment by monwarez** [comment]
That is good to hear.

**Pull request closed without merging**
