### PR TITLE
Effectively add a basic gitlab pipeline

### PR DESCRIPTION
**Pull request by adrienbernede**
Completes @davidbeckingsale work (#114) effectively adding the necessary yaml files.

### CODE REVIEW

**Comment by adrienbernede** [comment]
LGTM

**Comment by adrienbernede** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by nselliott** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
GitLab failures look like they are coming from a couple places: 1) the test job times out, and 2) some tests still SIGPIPE - I wonder if they are missing the macro.

**Comment by nselliott** [comment]
@davidbeckingsale I've identified the test directories that still have SIGPIPE and will take a look.  As for the timing out, the log from last Thursday says it started it started at 17:10 and timed out at 17:30, but it was supposed to have a 1 hour time limit?

**Comment by adrienbernede** [comment]
@nselliott This is because the allocation is shared with the build step and is 30 minute long (1 hour limit is in Gitlab, this is the slurm allocation I’m talking about).
I did that to use pdebug queue. Works fine on Umpire, but is a bit short on Samrai apparently.

**Comment by nselliott** [comment]
@adrienbernede I should do something to cut back the number of tests, at least when run through gitlab.  But first I'm going to address the SIGPIPE issue.  I think I have a fix.

**Comment by adrienbernede** [comment]
I can adapt the CI to run longer, it would be a shame if we did not run all the tests you want :)

**Comment by nselliott** [comment]
LGTM

**Comment by adrienbernede** [comment]
(Sorry wrong manipulation)
@nselliott do you have 2FA on Github? Looks like you LGTM comment had no effect.

**Comment by adrienbernede** [comment]
LGTM

**Comment by adrienbernede** [comment]
Test will pass with this.

**Comment by nselliott** [comment]
LGTM

**Comment by nselliott** [comment]
@adrienbernede I got rid of the SIGPIPE errors, but now every test that runs on 4 MPI ranks fails.  This wasn't happening before yesterday.  Also, it shows a successful green check here in github despite many tests failing.  Is there a keyword we need failing tests to produce so that failures will be reported as failures without us needing to dig up the log file?

**Comment by adrienbernede** [comment]
Hello @nselliott, I’m giving a look at the issue you mention.
How did you get rid of the SIGPIPE errors? Couldn’t find it in your changes, did I miss something was it in your environment?

**Comment by adrienbernede** [comment]
OK! I’m testing a fix for the multi-process failures.

**Comment by nselliott** [comment]
LGTM

**Comment by nselliott** [comment]
Still failing for all 4-processor tests and reporting success back here despite the failures.

**Comment by adrienbernede** [comment]
Thanks for the reminder. 👍

**Comment by adrienbernede** [comment]
LGTM

**Comment by adrienbernede** [comment]
@nselliott It now looks much better. Doesn’t it?

**Comment by nselliott** [comment]
Yes, thank you!

**Comment by nselliott** [comment]
I approved this but can't merge due to a conflict.  It is very small and I will resolve it.

**Comment by nselliott** [comment]
LGTM

**Pull request merged**
