### PR TITLE
Feature/healy22/more new ci

### PR DESCRIPTION
**Pull request by keithhealy**
Incorporated Noah's TPL building changes into the CI.  This should get the tests running on Ruby and Quartz.

### CODE REVIEW

**Comment by keithhealy** [comment]
I apologize for this taking as long as it has.

**Comment by keithhealy** [comment]
I'm going to go back to my attempt to integrate Radiuss shared CI.  This is ready to merge now though.

**Comment by nselliott** [comment]
Thanks, @keithhealy , it looks good and I'll merge it soon.  Did you try adding a blueos job as well?

**Review by nselliott — APPROVED** [review]

**Comment by keithhealy** [comment]
I did not try BlueOs. I'll do that now on a new branch.

**Pull request merged**
