### PR TITLE
bugfix accounts for src_shift in Raja variant of doArrayDataOperationOnBox

### PR DESCRIPTION
**Pull request by jonesholger**
We need to account for src_shift in the Raja variant of

void ArrayDataOperationUtilities<TYPE, OP>::doArrayDataOperationOnBox(
   ArrayData<TYPE>& dst,
   const ArrayData<TYPE>& src,
   const hier::Box& opbox,
   const hier::IntVector& src_shift,
   unsigned int dst_start_depth,
   unsigned int src_start_depth,
   unsigned int num_depth,
   const OP& op)

In the non-raja variant:

size_t src_begin = src_box.offset(opbox.lower() - src_shift)
      + src_start_depth * src_offset;

Example Fix for 2d variant
      case 2: {
         auto dest = get_view<2>(dst, d);
         auto source = get_const_view<2>(src, d);
         const int shift_i = src_shift[0];
         const int shift_j = src_shift[1];
         pdat::parallel_for_all(opbox, [=] SAMRAI_HOST_DEVICE (int j, int i) {
            op(dest(i, j), source(i-shift_i, j-shift_j));
         });
      } break;

In the long term we'll want a better fix which avoids offset calculation in the kernel

Also modified a couple of cmake related files.

### CODE REVIEW

**Comment by nselliott** [comment]
I need to figure out why the Travis build is failing.

**Comment by jdahm** [comment]
@nselliott Travis isn't building Umpire. We still need to add that and RAJA builds to `.travis.yml` on `feature/uvm-raja` and enable them in the SAMRAI build.

**Comment by nselliott** [comment]
@jdahm Aha, I didn't notice that this is a pull request into uvm-raja rather than master.

**Comment by jdahm** [comment]
I will add a commit to that branch that adds those packages.

**Comment by jonesholger** [comment]
Closed since RAJA added view shift capability

**Pull request closed without merging**
